### ISSUE TITLE
确定一下，摆放的编号是否一致？

### ISSUE THREAD

**Issue by luoluyao** [luoluyao/VoiceOrientation#7]
新的实验数据中，麦克风摆放的编号也是一致的吗？

**Comment by zkxvb** [comment]
对，只有距离在变化，其他都没有变


在 2017年12月20日，下午3:40，luoluyao <notifications@github.com<mailto:notifications@github.com>> 写道：


Assigned #7<https://github.com/luoluyao/VoiceOrientation/issues/7> to @zkxvb<https://github.com/zkxvb>.
